from django.urls import path
from . import views
urlpatterns = [
path('', views.index,name='index'),
path('index',views.index,name='index'),
path('loginvalidate',views.loginvalidate,name='loginvalidate'),
path('adminhome',views.adminhome,name='adminhome'),
path('adminlogin',views.adminlogin,name='adminlogin'),
path('userlogin',views.userlogin,name='userlogin'),
path('userhome',views.userhome,name='userhome'),
path('userloginvalidate',views.userloginvalidate,name='userloginvalidate'),
path('userregistervalidate',views.userregistervalidate,name='userregistervalidate'),
path('adminviewuser',views.adminviewuser,name='adminviewuser'),
path('userprofile',views.userprofile,name='userprofile'),
path('userprofileupdate',views.userprofileupdate,name='userprofileupdate'),
path('upupdate',views.upupdate,name='upupdate'),
path('inspectorlogin',views.inspectorlogin,name='inspectorlogin'),
path('inspectorregister',views.inspectorregistervalidate,name='inspectorregister'),
path('inspectorregistervalidate',views.inspectorregistervalidate,name='inspectorregistervalidate'),
path('viewinspector',views.viewinspector,name='viewinspector'),
path('insupdate',views.insupdate,name='insupdate'),
path('insprofileupdate',views.insprofileupdate,name='insprofileupdate'),
path('adminviewinspector',views.adminviewinspector,name='adminviewinspector'),
path('userdelete',views.userdelete,name="userdelete"),
path('inpectordelete',views.inpectordelete,name='inpectordelete'),
path('inspectorhome',views.inspectorhome,name='inspectorhome'),
path('usercomplaint',views.usercomplaint,name='usercomplaint'),
path('complaintsend',views.complaintsend,name='complaintsend'),
path('complaintform',views.complaintform,name='complaintform'),
path('adminviewcomplaints',views.adminviewcomplaints,name='adminviewcomplaints'),
path('approvecomplaints',views.approvecomplaints,name='approvecomplaints'),
path('deleteaction',views.deleteaction,name='deleteaction'),
path('inspectorviewcomplaints',views.inspectorviewcomplaints,name='inspectorviewcomplaints'),
path('replycomplaint',views.replycomplaint,name='replycomplaint'),
path('userviewcomplaints',views.userviewcomplaints,name='userviewcomplaints'),
path('trackcomplaints',views.trackcomplaints,name='trackcomplaints'),
path('insfeedback',views.insfeedback,name='insfeedback'),
path('userfeedback',views.userfeedback,name='userfeedback'),
path('inspectorseefeedback',views.inspectorseefeedback,name='inspectorseefeedback'),
path('userviewfeedback',views.userviewfeedback,name='userviewfeedback'),
path('adminuserfeedback',views.adminuserfeedback,name='adminuserfeedback'),
path('admininspectorfeedback',views.admininspectorfeedback,name='admininspectorfeedback'),

]
